FROM ghcr.io/dimkr/containers/c-dev:focal

RUN apt-get -qq update && apt-get -y install wget gnupg2
RUN wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - && printf "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main\ndeb http://apt.llvm.org/focal/ llvm-toolchain-focal main" > /etc/apt/sources.list.d/llvm.list && printf "Package: *\nPin: origin apt.llvm.org\nPin-Priority: 1001" > /etc/apt/preferences.d/llvm && apt-get -qq update && apt-get -y --allow-downgrades --no-install-recommends install clang-13 llvm-13-dev clang-14 llvm-14-dev && ln -s /usr/bin/clang-13 /usr/local/bin/clang
